### ISSUE TITLE
Error 21 when load on server

### ISSUE THREAD

**Issue by madhack2142** [mxswat/pz-Transmogv2#1]
keep getting er 21 when log in on my server. tried mod loader to load same order as server, transfered TransmogItems.txt from client to server, transfered TransmogItems.txt from server to client nothing has changed

with old version of mod everything works correct

**Comment by mxswat** [comment]
Are you still getting this error?

**Comment by madhack2142** [comment]
> Are you still getting this error?

you already answered me in steam
yes still getting, but when start client 1st time i can normally login on server and play, 2nd run = error 21
